version: "3.8"

services:
  chatbot-backend:
    image: taufansena/chatbot-backend:latest
    container_name: police-assistant-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OPENAI_API_KEY=
      - OPENROUTESERVICE_API_KEY=
      - OPENAI_MODEL=gpt-4o-mini
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
